#!/bin/bash

# start some nice programs
xsetroot -solid '#008080'
xset r rate 200 30

# locale
#export LC_ALL=ja_JP.UTF-8
#export LANG=ja_JP.UTF-8

# input method
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'
fcitx5 &

# yaskkserv2
yaskkserv2 --google-cache-filename="$HOME"/.local/share/fcitx5/skk/yaskkserv2.cache /usr/share/skk/SKK-JISYO.L.yaskkserv2

# backlight
if [ -f $HOME/.xbacklightrc ]; then
    munsell.py xbacklight s `cat $HOME/.xbacklightrc | grep ^brightness | gawk '{print($3)}'`
else
    munsell.py xbacklight s 3.5
fi

# screen saver off
xset s 1800 1800
xset -dpms

# capslock -> ctrl
setxkbmap -option ctrl:nocaps

# Statubar loop for dwm
while true; do
    dwm_statusbar.py xbacklight_bat_hms
    sleep 1s    # Update time every second
done &

